//! [`InputBackend`] event types for virtual pointer devices.

use std::path::PathBuf;
use std::sync::Arc;

use wayland_protocols_wlr::virtual_pointer::v1::server::zwlr_virtual_pointer_v1::ZwlrVirtualPointerV1;
use wayland_server::Resource;
use wayland_server::protocol::wl_seat::WlSeat;

use crate::backend::input::{self, Axis, AxisSource, InputBackend, InputTime, UnusedEvent};
use crate::output::{Output, WeakOutput};

use super::VirtualPointerData;

/// Backend type identifying events from `zwlr_virtual_pointer_v1`.
///
/// This backend is never constructed since virtual pointers are created by the
/// client; only the associated event types are used.
#[derive(Debug)]
pub struct VirtualPointerBackend;

impl InputBackend for VirtualPointerBackend {
    type Device = VirtualPointerDevice;

    type PointerAxisEvent = VirtualPointerAxisEvent;
    type PointerButtonEvent = VirtualPointerButtonEvent;
    type PointerMotionEvent = VirtualPointerMotionEvent;
    type PointerMotionAbsoluteEvent = VirtualPointerMotionAbsoluteEvent;

    type KeyboardKeyEvent = UnusedEvent;

    type GestureSwipeBeginEvent = UnusedEvent;
    type GestureSwipeUpdateEvent = UnusedEvent;
    type GestureSwipeEndEvent = UnusedEvent;
    type GesturePinchBeginEvent = UnusedEvent;
    type GesturePinchUpdateEvent = UnusedEvent;
    type GesturePinchEndEvent = UnusedEvent;
    type GestureHoldBeginEvent = UnusedEvent;
    type GestureHoldEndEvent = UnusedEvent;

    type TouchDownEvent = UnusedEvent;
    type TouchUpEvent = UnusedEvent;
    type TouchMotionEvent = UnusedEvent;
    type TouchCancelEvent = UnusedEvent;
    type TouchFrameEvent = UnusedEvent;

    type TabletToolAxisEvent = UnusedEvent;
    type TabletToolProximityEvent = UnusedEvent;
    type TabletToolTipEvent = UnusedEvent;
    type TabletToolButtonEvent = UnusedEvent;

    type SwitchToggleEvent = UnusedEvent;

    type SpecialEvent = UnusedEvent;
}

/// A pointer device created by a `zwlr_virtual_pointer_v1` client.
#[derive(Debug, Clone)]
pub struct VirtualPointerDevice {
    pub(super) pointer: ZwlrVirtualPointerV1,
    pub(super) data: Arc<VirtualPointerData>,
}

impl PartialEq for VirtualPointerDevice {
    fn eq(&self, other: &Self) -> bool {
        self.pointer == other.pointer
    }
}

impl Eq for VirtualPointerDevice {}

impl std::hash::Hash for VirtualPointerDevice {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.pointer.hash(state)
    }
}

impl VirtualPointerDevice {
    /// The seat this virtual pointer was created for, if any.
    pub fn wl_seat(&self) -> Option<&WlSeat> {
        self.data.seat.as_ref()
    }

    /// Output requested by the client, if it still exists.
    ///
    /// Absolute motion from this device is mapped onto this output (not the
    /// entire output layout).
    ///
    /// The output is stored as a weak reference so a long-lived client doesn't
    /// keep a removed output alive.
    pub fn output(&self) -> Option<Output> {
        self.data.output.as_ref().and_then(WeakOutput::upgrade)
    }
}

impl input::Device for VirtualPointerDevice {
    fn id(&self) -> String {
        format!("virtual-pointer-{}", self.pointer.id())
    }

    fn name(&self) -> String {
        String::from("virtual pointer")
    }

    fn has_capability(&self, capability: input::DeviceCapability) -> bool {
        matches!(capability, input::DeviceCapability::Pointer)
    }

    fn usb_id(&self) -> Option<(u32, u32)> {
        None
    }

    fn syspath(&self) -> Option<PathBuf> {
        None
    }
}

/// A relative motion event generated by a virtual pointer.
#[derive(Debug)]
pub struct VirtualPointerMotionEvent {
    pub(super) device: VirtualPointerDevice,
    pub(super) time: u32,
    pub(super) dx: f64,
    pub(super) dy: f64,
}

impl input::Event<VirtualPointerBackend> for VirtualPointerMotionEvent {
    fn time(&self) -> InputTime {
        InputTime::from_millis(self.time)
    }

    fn device(&self) -> VirtualPointerDevice {
        self.device.clone()
    }
}

impl input::PointerMotionEvent<VirtualPointerBackend> for VirtualPointerMotionEvent {
    fn delta_x(&self) -> f64 {
        self.dx
    }

    fn delta_y(&self) -> f64 {
        self.dy
    }

    fn delta_x_unaccel(&self) -> f64 {
        self.dx
    }

    fn delta_y_unaccel(&self) -> f64 {
        self.dy
    }
}

/// An absolute motion event generated by a virtual pointer.
///
/// The position is normalized from the client-chosen extents into `0.0..=1.0`.
#[derive(Debug)]
pub struct VirtualPointerMotionAbsoluteEvent {
    pub(super) device: VirtualPointerDevice,
    pub(super) time: u32,
    pub(super) x: u32,
    pub(super) y: u32,
    pub(super) x_extent: u32,
    pub(super) y_extent: u32,
}

/// Position along an axis as a `0.0..=1.0` fraction of the client's extent.
///
/// Although the protocol bounds the position by the extent, this doesn't stop
/// the client from sending something outside it, so clamp it here.
fn normalized(position: u32, extent: u32) -> f64 {
    f64::from(position.min(extent)) / f64::from(extent)
}

impl input::Event<VirtualPointerBackend> for VirtualPointerMotionAbsoluteEvent {
    fn time(&self) -> InputTime {
        InputTime::from_millis(self.time)
    }

    fn device(&self) -> VirtualPointerDevice {
        self.device.clone()
    }
}

impl input::AbsolutePositionEvent<VirtualPointerBackend> for VirtualPointerMotionAbsoluteEvent {
    fn x(&self) -> f64 {
        normalized(self.x, self.x_extent)
    }

    fn y(&self) -> f64 {
        normalized(self.y, self.y_extent)
    }

    fn x_transformed(&self, width: i32) -> f64 {
        f64::max(self.x() * f64::from(width), 0.0)
    }

    fn y_transformed(&self, height: i32) -> f64 {
        f64::max(self.y() * f64::from(height), 0.0)
    }
}

impl input::PointerMotionAbsoluteEvent<VirtualPointerBackend> for VirtualPointerMotionAbsoluteEvent {}

/// A button event generated by a virtual pointer.
#[derive(Debug)]
pub struct VirtualPointerButtonEvent {
    pub(super) device: VirtualPointerDevice,
    pub(super) time: u32,
    pub(super) button: u32,
    pub(super) state: input::ButtonState,
}

impl input::Event<VirtualPointerBackend> for VirtualPointerButtonEvent {
    fn time(&self) -> InputTime {
        InputTime::from_millis(self.time)
    }

    fn device(&self) -> VirtualPointerDevice {
        self.device.clone()
    }
}

impl input::PointerButtonEvent<VirtualPointerBackend> for VirtualPointerButtonEvent {
    fn button_code(&self) -> u32 {
        self.button
    }

    fn state(&self) -> input::ButtonState {
        self.state
    }
}

/// Scroll state accumulated for one axis between two `frame` requests.
#[derive(Debug, Default, Clone, Copy)]
pub(super) struct PendingAxis {
    pub(super) value: f64,
    /// Discrete steps, if the client sent an `axis_discrete` request for this
    /// axis. [`None`] when it only sent `axis`, which carries no step count.
    pub(super) v120: Option<i32>,
}

/// Scroll state accumulated between two `frame` requests.
#[derive(Debug, Default)]
pub(super) struct PendingFrame {
    pub(super) time: u32,
    pub(super) source: Option<AxisSource>,
    /// Pending state for the horizontal and vertical axes.
    pub(super) axes: [Option<PendingAxis>; 2],
}

pub(super) fn axis_index(axis: Axis) -> usize {
    match axis {
        Axis::Horizontal => 0,
        Axis::Vertical => 1,
    }
}

/// An axis event generated by a virtual pointer, covering one `frame`.
#[derive(Debug)]
pub struct VirtualPointerAxisEvent {
    pub(super) device: VirtualPointerDevice,
    pub(super) frame: PendingFrame,
}

impl input::Event<VirtualPointerBackend> for VirtualPointerAxisEvent {
    fn time(&self) -> InputTime {
        InputTime::from_millis(self.frame.time)
    }

    fn device(&self) -> VirtualPointerDevice {
        self.device.clone()
    }
}

impl input::PointerAxisEvent<VirtualPointerBackend> for VirtualPointerAxisEvent {
    fn amount(&self, axis: Axis) -> Option<f64> {
        self.frame.axes[axis_index(axis)].map(|pending| pending.value)
    }

    fn amount_v120(&self, axis: Axis) -> Option<f64> {
        if !matches!(self.source(), AxisSource::Wheel | AxisSource::WheelTilt) {
            return None;
        }

        // Note this can be `None` for a wheel source, even though the trait
        // says otherwise. A client may send `axis` without `axis_discrete` for
        // a wheel. Don't specify it unless it's non-zero so the compositor
        // falls back to `amount()` if it's unknown.
        self.frame.axes[axis_index(axis)].and_then(|pending| pending.v120.map(f64::from))
    }

    fn source(&self) -> AxisSource {
        // wlroots defaults to wheel when the client doesn't send `axis_source`.
        self.frame.source.unwrap_or(AxisSource::Wheel)
    }

    fn relative_direction(&self, _axis: Axis) -> input::AxisRelativeDirection {
        input::AxisRelativeDirection::Identical
    }
}
