//! [`InputBackend`] event types for virtual keyboard devices.

use std::path::PathBuf;
use std::sync::Arc;

use wayland_protocols_misc::zwp_virtual_keyboard_v1::server::zwp_virtual_keyboard_v1::ZwpVirtualKeyboardV1;
use wayland_server::Resource;
use wayland_server::protocol::wl_seat::WlSeat;

use crate::backend::input::{self, InputBackend, InputTime, UnusedEvent};

use super::VirtualKeyboardData;

/// Backend type identifying events from `zwp_virtual_keyboard_v1`.
///
/// This backend is never constructed since virtual keyboards are created by the
/// client; only the associated event types are used.
#[derive(Debug)]
pub struct VirtualKeyboardBackend;

impl InputBackend for VirtualKeyboardBackend {
    type Device = VirtualKeyboardDevice;
    type KeyboardKeyEvent = VirtualKeyboardKeyEvent;

    type PointerAxisEvent = UnusedEvent;
    type PointerButtonEvent = UnusedEvent;
    type PointerMotionEvent = UnusedEvent;
    type PointerMotionAbsoluteEvent = UnusedEvent;

    type GestureSwipeBeginEvent = UnusedEvent;
    type GestureSwipeUpdateEvent = UnusedEvent;
    type GestureSwipeEndEvent = UnusedEvent;
    type GesturePinchBeginEvent = UnusedEvent;
    type GesturePinchUpdateEvent = UnusedEvent;
    type GesturePinchEndEvent = UnusedEvent;
    type GestureHoldBeginEvent = UnusedEvent;
    type GestureHoldEndEvent = UnusedEvent;

    type TouchDownEvent = UnusedEvent;
    type TouchUpEvent = UnusedEvent;
    type TouchMotionEvent = UnusedEvent;
    type TouchCancelEvent = UnusedEvent;
    type TouchFrameEvent = UnusedEvent;

    type TabletToolAxisEvent = UnusedEvent;
    type TabletToolProximityEvent = UnusedEvent;
    type TabletToolTipEvent = UnusedEvent;
    type TabletToolButtonEvent = UnusedEvent;

    type SwitchToggleEvent = UnusedEvent;

    type SpecialEvent = VirtualKeyboardSpecialEvent;
}

/// A keyboard device created by a `zwp_virtual_keyboard_v1` client.
///
/// The device is only actually added once the client has sent a keymap request,
/// which may or may not carry a keymap (see [`Self::keymap`]).
#[derive(Debug, Clone)]
pub struct VirtualKeyboardDevice {
    pub(super) keyboard: ZwpVirtualKeyboardV1,
    pub(super) data: Arc<VirtualKeyboardData>,
}

impl PartialEq for VirtualKeyboardDevice {
    fn eq(&self, other: &Self) -> bool {
        self.keyboard == other.keyboard
    }
}

impl Eq for VirtualKeyboardDevice {}

impl std::hash::Hash for VirtualKeyboardDevice {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.keyboard.hash(state)
    }
}

impl VirtualKeyboardDevice {
    /// The seat this virtual keyboard was created for.
    pub fn wl_seat(&self) -> &WlSeat {
        &self.data.seat
    }

    /// The client's keymap, as `XKB_KEYMAP_FORMAT_TEXT_V1`.
    ///
    /// This device's keycodes must be processed using the keymap, which isn't
    /// usually the default one, so it needs to be activated (e.g. with
    /// [`KeyboardHandle::set_keymap_from_string`](crate::input::keyboard::KeyboardHandle::set_keymap_from_string))
    /// before processing the device's key events.
    ///
    /// [`None`] when the client sent the `no_keymap` format, meaning its
    /// keycodes are to be read with whatever keymap the seat already has, so
    /// there is nothing to activate. Also [`None`] before the device is added.
    pub fn keymap(&self) -> Option<Arc<str>> {
        self.data.keymap.lock().unwrap().clone()
    }
}

impl input::Device for VirtualKeyboardDevice {
    fn id(&self) -> String {
        format!("virtual-keyboard-{}", self.keyboard.id())
    }

    fn name(&self) -> String {
        String::from("virtual keyboard")
    }

    fn has_capability(&self, capability: input::DeviceCapability) -> bool {
        matches!(capability, input::DeviceCapability::Keyboard)
    }

    fn usb_id(&self) -> Option<(u32, u32)> {
        None
    }

    fn syspath(&self) -> Option<PathBuf> {
        None
    }
}

/// A key event generated by a virtual keyboard.
#[derive(Debug)]
pub struct VirtualKeyboardKeyEvent {
    pub(super) device: VirtualKeyboardDevice,
    pub(super) time: u32,
    pub(super) key: u32,
    pub(super) state: input::KeyState,
}

impl input::Event<VirtualKeyboardBackend> for VirtualKeyboardKeyEvent {
    fn time(&self) -> InputTime {
        InputTime::from_millis(self.time)
    }

    fn device(&self) -> VirtualKeyboardDevice {
        self.device.clone()
    }
}

impl input::KeyboardKeyEvent<VirtualKeyboardBackend> for VirtualKeyboardKeyEvent {
    fn key_code(&self) -> input::Keycode {
        // Keycodes from the protocol are offset by 8 from raw xkb keycodes,
        // matching `wl_keyboard` and evdev.
        input::Keycode::from(self.key + 8)
    }

    fn state(&self) -> input::KeyState {
        self.state
    }

    fn count(&self) -> u32 {
        1
    }
}

/// Virtual keyboard requests that have no generic [`InputEvent`] equivalent.
///
/// [`InputEvent`]: crate::backend::input::InputEvent
#[derive(Debug)]
pub enum VirtualKeyboardSpecialEvent {
    /// The client replaced the keymap of a device that was already added.
    ///
    /// [`VirtualKeyboardDevice::keymap`] now returns the new one.
    KeymapChanged {
        /// The virtual keyboard device
        device: VirtualKeyboardDevice,
    },
    /// The client set the modifier state directly, rather than through key
    /// presses.
    ///
    /// The masks are relative to the device's keymap (or the seat's, if it sent
    /// no keymap) and must be applied only while that keymap is active, using
    /// [`XkbContext::set_modifier_mask`](crate::input::keyboard::XkbContext::set_modifier_mask).
    Modifiers {
        /// The virtual keyboard device
        device: VirtualKeyboardDevice,
        /// Depressed (pressed) modifier mask
        mods_depressed: u32,
        /// Latched modifier mask
        mods_latched: u32,
        /// Locked modifier mask
        mods_locked: u32,
        /// Locked layout group index
        group: u32,
    },
}
